### ISSUE TITLE
run.php - общедоступный

### ISSUE THREAD

**Issue by MrKira34** [Roscenzura-com/antiddos#3]
По поводу файла /<папка скрипта>/cron/run.php
И команд:
/<папка скрипта>/cron/run.php?action=clearcount
/<папка скрипта>/cron/run.php?action=clearban
Я правильно понимаю, что тот, кто атакует сайт, может проанализировать структуру сайта, найти этот php файл и если он как-то выйдет на ваш скрипт, шанс этого очень большой. То перейдя по URL: НашДомен/<папка скрипта>/cron/run.php?action=clearban очистит список заблокированных IP адресов или clearcount и продолжит дальше атаковать сайт, периодически запуская run.php ?

**Comment by Roscenzura-com** [comment]
Поэтому и надо папку уникальную делать. А как атакующий узнает имя папки? Никак. 
Как вариант, вы можете wget запрос делать от уникального user agent. Я в теме на форуме расписал как.

**Comment by Roscenzura-com** [comment]
По ссылке URL: НашДомен/<папка скрипта>/cron/run.php?action=clearban
Удаляются только старые IP, для которых истек лимит. И только из папки бан, из Cloudflare пока надо удалять самостоятельно, но на автомате.

Впрочем, я добавил .htaccess. И крон файл вы можете вызывать не wget-ом, а PHP.
